#!/bin/bash

#sudo service redis restart
#sudo service mosquitto restart
#sudo pkill redis-cli
#redis-cli monitor &
sudo pkill peerjs
sudo peerjs --port 8999 --key peerjs --path /peer \
       --sslkey /etc/letsencrypt/live/vango.me-0002/privkey.pem \
       --sslcert /etc/letsencrypt/live/vango.me-0002/fullchain.pem &
ruby exe/init.rb $*
